export const FETCHING_BOOKS = "FETCHING_BOOKS";
export const SUCCESS_FETCHED_BOOKS = "SUCCESS_FETCHED_BOOKS";
export const FAILURE_FETCHED_BOOKS = "FAILURE_FETCHED_BOOKS";
export const SELECTED_BOOK = "SELECTED_BOOK";
export const CHANGED_FILTER = "CHANGED_FILTER";
